version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 141939821191.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - mvn clean package -DskipTests
      - ls -la target/
      - cat Dockerfile
      - docker build --platform linux/amd64 --progress=plain -t 141939821191.dkr.ecr.us-east-1.amazonaws.com/demo-springboot-app:latest . 2>&1
      - docker images

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 141939821191.dkr.ecr.us-east-1.amazonaws.com/demo-springboot-app:latest
      - printf '[{"name":"demo-springboot-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
