version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 141939821191.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - mvn clean package -DskipTests
      - echo "--- Listing target folder ---"
      - ls -la target/                          # ✅ confirm JAR was created
      - echo "--- Building Docker image ---"
      - docker build -t 141939821191.dkr.ecr.us-east-1.amazonaws.com/demo-springboot-app:latest .
      - echo "--- Docker images available ---"
      - docker images                           # ✅ confirm image exists after build

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 141939821191.dkr.ecr.us-east-1.amazonaws.com/demo-springboot-app:latest
      - printf '[{"name":"spring-container","imageUri":"%s"}]' 141939821191.dkr.ecr.us-east-1.amazonaws.com/demo-springboot-app:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json